accounts/urls.py
from django.urls import path,include
from .import views

app_name = 'accounts'

urlpatterns =[
   path('sign_up/', views.sign_up_view, name='sign_up'),
   path('log_in/', views.log_in_view, name='log_in'),
   path('log_out/', views.log_out_view, name='log_out'),

]

articles/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

app_name= 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.article_create, name='article.create'),
    path('article/', views.article_list, name='list_of_articles'),
    path('^(?P<slug>[\w-]+)/', views.article_details, name='details_of_articles'),
    path('our_team/', views.our_team, name='our_team'),
    path('majors/', views.majors, name='majors'),
    path('admissions/', views.admissions, name='admissions'),
    path('campus/', views.campus, name='campus'),
]

contact/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

app_name= 'contact'
urlpatterns = [
    path('contact/', views.contact, name='contact'),
#     path('^(?P<slug_path>[\w-]+)/', views.item_details, name='details_of_items'),

]

final/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('lost_found.urls')),
    path('',include('contact.urls')),
    path('',include('accounts.urls')),
    path('',include('articles.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

lost_found/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views

app_name= 'items'
urlpatterns = [
    path('lost_found/', views.item_list, name='list_of_items'),
#     path('^(?P<slug_path>[\w-]+)/', views.item_details, name='details_of_items'),

]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
	article_title = models.CharField(max_length=100)
	slug = models.SlugField(unique="True")
	body = models.TextField()
	date = models.DateTimeField(auto_now_add = True)
	thumb = models.ImageField(default='default.png',upload_to='post_image',blank=True)
	author = models.ForeignKey(User, default=None, on_delete = models.DO_NOTHING, null=True)

	def __str__(self):
		return self.article_title

	def snippet(self):
		return self.body[:370]+ " ..."

contact/models.py
from django.db import models

# Create your models here.

lost_found/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class lost_found(models.Model):
	item_name = models.CharField(max_length=100)
	slug_path = models.SlugField(unique="True")
	item_description = models.TextField()
	date = models.DateTimeField(auto_now_add = True)
	image = models.ImageField(default='default.png',upload_to='post_image',blank=True)
	author = models.ForeignKey(User, default=None, on_delete = models.DO_NOTHING, null=True)

	def __str__(self):
		return self.item_name

	def snippet(self):
		return self.item_description[:500]

articles/forms.py
from django import forms
from lost_found import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model=models.lost_found
		fields=['item_name','item_description','slug_path','image']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.
def sign_up_view(request):
	if request.method == 'POST':
		form=UserCreationForm(request.POST)
		if form.is_valid():
			 user=form.save()
			 login(request, user)

			 return redirect('articles:index')
	else:
			form =UserCreationForm()
	return render(request, 'sign_up.html', {'form':form})



def log_in_view(request):
	if request.method == 'POST':
		form=AuthenticationForm(data=request.POST)
		if form.is_valid():
			user=form.get_user()
			login(request,user)
					 
			if'next'in request.POST:
					
				return redirect(request.POST.get('next'))
		 
			else:

				return redirect('articles:index')
	else:
			form =AuthenticationForm()
	return render(request, 'log_in.html', {'form':form})

def log_out_view(request):
	if request.method == 'POST':
			logout(request)
			return redirect('articles:index')
		
	# else:
	#     form =AuthenticationForm()
	# return render(request, 'log_in.html', {'form':form})

articles/views.py
from django.shortcuts import render,redirect
from articles.models import Article
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.from article_app.models import Article
# Create your views here.
def article_list(request):
	articles_from_database = Article.objects.all().order_by('date')
	return render(request, 'article.html', {'articles_from_database':articles_from_database})
# def main_page(request):
# 	return render(request, 'index.html')

def article_details(request, slug):
	article = Article.objects.get(slug=slug)
	return render(request, 'each_article.html', {'article':article})

@login_required(login_url='/log_in/')
def article_create(request):
	if request.method =='POST':
		form=forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			instance=form.save(commit='False')
			instance.author = request.user
			instance.save()
			return redirect('items:list_of_items')
	else:
	    form =forms.CreateArticle()
	return render(request, 'article_create.html', {'form':form})

def index(request):
	articles_from_database = Article.objects.all().order_by('date')
	return render(request, 'index.html', {'articles_from_database':articles_from_database})

def our_team(request):
    return render(request, 'our_team.html')

def majors(request):
    return render(request, 'majors.html')


def admissions(request):
    return render(request, 'admissions.html')

def campus(request):
    return render(request, 'campus.html')

contact/views.py
from django.shortcuts import render,redirect
from lost_found.models import lost_found
from django.contrib.auth.decorators import login_required


def contact(request):
	return render(request, 'contact.html')

lost_found/views.py
from django.shortcuts import render,redirect
from lost_found.models import lost_found
from django.contrib.auth.decorators import login_required

# Create your views here.from article_app.models import Article
# Create your views here.
def item_list(request):
	items_from_database = lost_found.objects.all().order_by('date')
	return render(request, 'lost_found.html', {'items_from_database':items_from_database})
# def main_page(request):
# 	return render(request, 'index.html')

# def item_details(request, slug_path):
# 	item_article = lost_found.objects.get(slug_path = slug_path)
# 	return render(request, 'lost_found_items.html', {'item_article':item_article})

templates/admissions.html
{% extends "index.html" %}
{%load static%}
<!--page for all information about admission of the web-->
{% block content %}


<div class="admissions container">
    <ul class="collapsible">
        <li>
            <div class="collapsible-header"><i class="material-icons">school</i>Admissions for 2020.</div>
            <div class="collapsible-body">
                <span>On approval of regulations on admission to higher education institutions, transfer, reinstatement and exclusion of students.
                      <br> <b>for whole information download below link ... </b><br>
                </span>
                <a class="waves-effect btn blue darken-2" href="https://drive.google.com/file/d/1IgsDCNvOwjlG3yFqtp527S5uOh9bBR8I/view?usp=sharing"><i class="material-icons left ">file_download</i>Download</a></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">group</i>For International Students</div>
            <div class="collapsible-body">
                <span>
                    <b>Education</b> <br>Academic year in NamSU continues from September to June (01.09-30.06). Duration of Study: Bachelor’s
                    Degree - 4 academic years; Master‘s Degree - 2 academic years; Doctoral Degree (PhD, DSc) - 3 (4) academic
                    years, depending on the Faculty (field of study). <br> Our programs are available to study full time at all faculties.
                    Enrolling to the NamSU is based on the on the interview.<br> For additional information, please contact to the Admission
                    committee. As a rule, study in NamSU is conducted in Russian and Uzbek, so good preliminary language training is required.<br>
                    <b>for whole information download below link ... </b><br>
                </span>
                <a class="btn tooltipped waves-effect blue darken-2" href="https://drive.google.com/file/d/1wNdcErF-4a2-scbZemA78gFDMN7xceVp/view?usp=sharing" data-position="top" data-tooltip="International Students"><i class="material-icons left ">file_download</i>Download</a>
            </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">report</i>Note for applicants</div>
            <div class="collapsible-body">
                <span>
                    Applicants must submit the relevant documents to the Admissions Office, the information corresponding to the submitted documents
                    must confirm that it is entered correctly in the applicant database. Upon completion of the admission process, the applicant
                    appeals (complaints) are not taken into account. The applicant will take the test on the date and time specified in the permit..
                    <br> <b>During the test, the applicant has the following rights: </b> <br>- use the questionnaire as a draft; <br>
                    - complete test assignments ahead of schedule, then group test materials in ord hand over to the supervisor and leave the test site. <br>
                    - On the day of the test, the applicant will enter the building at 07:00 (second shift at 13:00).to the building until 07:30 (second
                    shift at 13:30) only with the applicant's permission and passport systematic access through personal identification devices and video
                    recording devices, -test with strict adherence to the rules of testing, in the first shift from 07:30 to 08:00in the second shift from
                    14:30 to 15:00 have to do the following: <br>- check the compatibility of the test book and the corresponding numerical answer sheets; <br>
                    - check the integrity of the test materials and immediately notify the group supervisor if any defects are found to give; <br>
                    - ensure that the answer sheet is completed correctly; <br> - last name, first name, patronymic in the appropriate place on the cover
                    of the test book and on the answer sheet write your name and sign; <br> - Copy and paste the answer sheet number in the appropriate place
                    on the applicant's permit and title page put <br>- the special code indicated on the title page and the code of the educational institution
                    in the place indicated on the answer sheet Copy and paste the appropriate circles. <br><b>for whole information download below link ... </b><br>
                </span>
                <a class="waves-effect btn blue darken-2" href="https://drive.google.com/file/d/13ixjl3QGtkuH1HvBMWqgmoc6hi-pVNaI/view?usp=sharing"><i class="material-icons left ">file_download</i>Download</a>
            </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">today</i>Admission plan for the 2020 academic year</div>
            <div class="collapsible-body">
                <span>Namangan State University schedule for 2020 Academic year undergraduates by each major: <br>
                <b>download schedule below link ... </b><br>
                </span>
                <a class="waves-effect btn blue darken-2" href="https://drive.google.com/file/d/1GCSSMgiN3dwbSVdVpaRR0tLOpDGEPlaA/view?usp=sharing"><i class="material-icons left ">file_download</i>Download</a>
            </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">streetview</i>Creative exam results for the 2019-2020 academic year</div>
            <div class="collapsible-body"><span>During 2019 and 2020, the number of applicants to creative exams are increased sharply. Creative exam results for the 2019-2020 academic year
            <br><b>check all last year scores below link ... </b><br></span><a class="waves-effect btn blue darken-2" href="https://drive.google.com/file/d/14mIPvuFiMbOYUsRDnQxweykxg40LVG5A/view?usp=sharing"><i class="material-icons left ">file_download</i>Download</a>
            </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="material-icons">visibility</i>2019-2020 academic year students scores</div>
            <div class="collapsible-body">
                <span>2019-2020 academic year students scores.<br><b>check all last year scores below link ... </b><br>
                </span><a class="waves-effect btn blue darken-2" href="https://drive.google.com/file/d/1Ar8ZU1pLEdng4om-RAgJlVvdnmlYWIoj/view?usp=sharing"><i class="material-icons left ">file_download</i>Download</a>
            </div>
        </li>
    </ul>

</div>


{% endblock content %}

templates/article.html
{% extends "index.html" %}
{%load static%}
<!--page for all articles-->
{% block content %}
    {% for article in articles_from_database %}
		<div class="each_article container hoverable">
			<div class="row">
				<div class="col s7">
					<h5>
						<a href="{% url 'articles:details_of_articles' slug=article.slug %}">{{article.article_title}}</a>
					</h5>
			        <p class="flow-text"><a href="{% url 'articles:details_of_articles' slug=article.slug %}">{{article.snippet}}</a></p>
				    <p>
						<a href="{% url 'articles:details_of_articles' slug=article.slug %}" class="date_of_post" style="color:grey;">{{article.date}}</a>
					</p>
				</div>
				<div class="col s5">
			          <img class="responsive-img" src="{{article.thumb.url}}">
				</div>
			</div>
		</div>
	{%endfor%}

{% endblock content %}

templates/article_create.html
{% extends "index.html" %}
{% block content %}
<!--starting of creating article page.-->
	<div class="create-article container z-depth-3 hoverable">
		<form class="site-form input-field" method="POST" action="{% url 'articles:article.create'%}" enctype="multipart/form-data">
			{{form.as_p}}
			{%csrf_token%}
			<input type="submit" class="btn waves-effect waves-light blue darken-2 " value="CREATE" name="">
		</form>
	</div>

{% endblock content %}

templates/contact.html
{% extends "index.html" %}
{%load static%}
<!--page for all articles-->
{% block content %}


<div class="container z-depth-3 hoverable flow-text contact row">

        <div class="col s5">
            <div class="row">
                <div class="input-field ">
                    <i class="material-icons prefix blue-text text-darken-3">account_circle</i>
                    <input id="icon_prefix" type="text" class="validate">
                    <label for="icon_prefix">First Name</label>
                </div>

            </div>
            <div class="row">
                <div class="input-field ">
                    <i class="material-icons prefix blue-text text-darken-3">phone</i>
                    <input id="icon_telephone" type="tel" class="validate">
                    <label for="icon_telephone">Telephone</label>
                </div>

            </div>
            <div class="row">
                <div class="input-field ">
                    <i class="material-icons prefix blue-text text-darken-3">email</i>
                    <input id="email" type="email" class="validate">
                    <label for="email">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field ">
                    <i class="material-icons prefix blue-text text-darken-3">mode_edit</i>
                    <textarea id="textarea2" class="materialize-textarea" data-length="120"></textarea>
                    <label for="textarea2">Textarea</label>
                </div>
            </div>
        </div>
        <div class="col s7">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3009.830810439716!2d71.84308531577216!3d41.028957326100155!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38bb4c0f3da09121%3A0x96efaff1734c248c!2sNamangan%20State%20University!5e0!3m2!1sen!2skr!4v1586523430268!5m2!1sen!2skr" width="500" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>


</div>


{% endblock content %}

templates/each_article.html
{% extends "index.html" %}
{% block content %}
<!--here you can navigate each article-->

	    <div class="article_detail container">
		     <h4><a href="">{{article.article_title}}</a></h4>
		     <img class="responsive-img" src="{{article.thumb.url}}">
			 <p><a href="#">{{article.body}}</a></p>
		     <p><a href="#">{{article.date}}</a></p>
		</div>



{% endblock content %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<!--	title of project-->
	<title>NNU</title>

<!--all links CSS, Materialize, GoogleFonts, GoogleIcons are here-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/f15df23be3.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'sass/style.css' %}">
</head>
<!--body content start from here-->
<body>
<header>
<!--	header with full codes of navbar-->
	<div class="navbar-fixed">
      <nav class="nav-extended blue darken-3 sidenav-trigger">
        <div class="nav-wrapper">
<!--      <a href="{% url 'articles:index'%}" class="brand-logo"> <img src="{% static 'images/logo2.png' %}" alt="My image" style="height: 60px; margin-top: 0px;"></a>-->
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class=" hide-on-med-and-down" >
		    <li class="tab"><a class="active" href="{% url 'articles:index'%}">Home <i class="fas fa-home"></i></a></li>
		    <li class="tab"><a href="{% url 'articles:list_of_articles'%}">News</a></li>
		    <li class="tab"><a href="{% url 'articles:admissions'%}">Admissions</a></li>
		    <li class="tab"><a href="{% url 'articles:majors'%}">Majors </a></li>
		    <li class="tab"><a href="{% url 'articles:campus'%}">Structure </a></li>
		    <li class="tab"><a href="{% url 'items:list_of_items'%}">Lost/Found</a></li>
		    <li class="tab"><a href="{% url 'articles:our_team'%}">Our Team</a></li>
		    <li class="tab"><a href="{% url 'contact:contact'%}">Contact Us</a></li>

          </ul>
		  <ul id="nav-mobile" class="right " >
			{%if user.is_authenticated %}
			<li><form class="log_out" method="POST" action="{% url 'accounts:log_out'%}">
				{% csrf_token%}
				<button type="submit" class="btn waves-effect waves-light blue darken-2">Log OUT </button>
			</form>
			</li>
			{% else %}
			<div class="nav_index_status">
				<li><a href="{% url 'accounts:log_in'%}">Login <i class="fas fa-user-tie"></i></a></li>
				<li><a href="{% url 'accounts:sign_up'%}">Sign up <i class="fas fa-user-plus"></i></a></li>
				<li><a href="{% url 'articles:article.create'%} ">Create idea <i class="fas fa-file-alt"></i></a></li>
			</div>
			{% endif %}
		  </ul>
		</div>
      </nav>
	</div>
	<ul class="sidenav" id="mobile-demo">
		<li class="tab"><a class="active" href="{% url 'articles:index'%}">Home <i class="fas fa-home"></i></a></li>
		<li class="tab"><a href="{% url 'articles:list_of_articles'%}">News</a></li>
		<li class="tab"><a href="{% url 'articles:admissions'%}">Admissions</a></li>
		<li class="tab"><a href="{% url 'articles:majors'%}">Majors </a></li>
		<li class="tab"><a href="{% url 'articles:campus'%}">Structure </a></li>
		<li class="tab"><a href="{% url 'items:list_of_items'%}">Lost/Found</a></li>
		<li class="tab"><a href="{% url 'articles:our_team'%}">Our Team</a></li>
		<li class="tab"><a href="{% url 'contact:contact'%}">Contact Us</a></li>
	</ul>
</header>
<!--main part of program will start from here-->
<main>
   {% block content %}
<!--	slider of the web in main page-->
	<div class="slider responsive-img" >
		<ul class="slides ">
			<li>
				<img  src="{% static 'images/banner01.jpg' %}"  alt="My image" > <!-- Slider 1st image -->
			</li>
			<li>
				<img src="{% static 'images/banner03.jpg' %}" alt="My image" >  <!-- Slider 2nd image -->
			</li>
			<li>
				<img src="{% static 'images/banner02.jpg' %}" alt="My image" >  <!-- Slider 3rd image -->
			</li>
			<li>
				<img src="{% static 'images/banner04.jpg' %}" alt="My image" >  <!-- Slider 4th image -->
			</li>
		</ul>
	</div>

<!--	finish slider and start university info part of web starts from here-->
	<div class="university_info">
	  <div class="container row ">
		<div class="col s3 ">
			<img src="{% static 'images/logo2.png' %}"  class="responsive-img"  alt="My university logo" >
		</div>
		<div class="col s9" style="color: dimgrey">
		<h4>Namangan State University </h4>
			<div>
				<p>Namangan State University (NamSU) was established in 1942 as a pedagogical institute. It is in Namangan
				province which has almost 2.8 mln population with 7900 km2 area locatedin eastern part on Uzbekistan, considered
				one of the strategically important area. Nowadays NamSU has over 15000 students in bachelor and master degree programs.
				</p>
			</div>
		</div>
	  </div>
	</div>

<!--     Slider and brief info finished and now time to parallax effect in my web-->
	<div class="parallax-container">
		<div class="parallax"><img src="{% static 'images/new.jpg' %}"  alt="My image" ></div>
	</div>
<!--	Parallax effect finish in here-->

<!--	my last 4 icons code start from here-->
	<div class="row container brief_info" style="color: dimgrey">
		<div class="col s3">
			<div class="center promo-example">
				<a href="{% url 'articles:admissions'%}"><i class="large material-icons blue-text text-darken-3">school</i></a>
			<h5 class="promo-caption">Admission</h5>
			<p class="light center">Admission page helps to newcomers and other students to check the last year recordings. </p>
			</div>
		</div>
		<div class="col s3">
			<div class="center promo-example">
				<i class="large material-icons blue-text text-darken-3">forum</i>
				<h5 class="promo-caption">Contact </h5>
				<p class="light center">Each student can contact with our global students support office(or email and phone). </p>
			</div>
		</div>
		<div class="col s3">
			<div class="center promo-example">
				<a href="http://e-library.namdu.uz/"><i class="large material-icons blue-text text-darken-3">get_app</i></a>
				<h5 class="promo-caption">Download</h5>
				<p class="light center">Our community support students with extra resources and also last recordings.</p>
			</div>
		</div>
		<div class="col s3">
			<div class="center promo-example">
				<a href="{% url 'articles:list_of_articles'%}"><i class="large material-icons blue-text text-darken-3">event_available</i></a>
				<h5 class="promo-caption">News</h5>
				<p class="light center">In news page, students can read last news about our university or education system.</p>
			</div>
		</div>
	</div>
<!--brief info icons code finished in here-->
	{% endblock content %}
<!--	end of index codes are here-->

	<div class="fixed-action-btn ">

		<a class="btn-floating btn-large blue darken-3 " >
			<i class="large material-icons ">mode_edit</i>
		</a>
		<ul>
			<li><a href="https://materializecss.com/floating-action-button.html" class="btn-floating blue darken-3"><i class="material-icons">insert_chart</i></a></li>
			<li><a class="btn-floating blue darken-3"><i class="material-icons">format_quote</i></a></li>
			<li><a class="btn-floating blue darken-3"><i class="material-icons">publish</i></a></li>
			<li><a class="btn-floating blue darken-3"><i class="material-icons">attach_file</i></a></li>

		</ul>
	</div>
</main>
<!--here is the footer-->
<footer class="page-footer blue darken-3">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">Namangan State University</h5>
				<p class="grey-text text-lighten-4">Namangan State University is your right choice.</p>
			</div>
			<div class="col l2 offset-6 s6">
			<h5 class="white-text">Follow us</h5>
			<ul>
				<li><a class="grey-text text-lighten-3" href="https://www.youtube.com/watch?v=Sq8liiRHr8M"><i class="fab fa-youtube"></i> YouTube</a></li>
				<li><a class="grey-text text-lighten-3" href="https://www.facebook.com/namangandavlatuniversiteti/"><i class="fab fa-facebook-square"></i> Facebook </a></li>
				<li><a class="grey-text text-lighten-3" href="https://www.instagram.com/namangan_davlat_universiteti/"><i class="fab fa-instagram"></i> Instagram </a></li>
				<li><a class="grey-text text-lighten-3" href="http://www.namdu.uz/en"><i class="fab fa-google"></i> Google</a></li>
			</ul>
		</div>
			<div class="col l2 offset-6 s6">
				<h5 class="white-text">Contact us</h5>
				<ul>
					<li><a class="grey-text text-lighten-3" href="#"><i class="fas fa-envelope-open-text"></i> Email: info@namdu.uz</a></li>
					<li><a class="grey-text text-lighten-3" href="#"><i class="fas fa-phone-volume"></i>   Phone: 010-655-65-47</a></li>

					<li><a class="grey-text text-lighten-3" href="#"><i class="fas fa-map-marker-alt"></i> Address: Namangan region, Uzbekistan</a></li>

				</ul>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			© 2020 Copyright U.Azizbek. All rights reserved.
			<a class="grey-text text-lighten-4 right" href="#!">Capstone Design </a>
		</div>
	</div>
</footer>

<!--here is the extra scripts which I used to apply Materialize codes. -->
<script>
	$(document).ready(function(){
		$('.sidenav').sidenav();
		$('.parallax').parallax();
		$('.fixed-action-btn').floatingActionButton();
		$('input#input_text, textarea#textarea2').characterCounter();
		$('.tooltipped').tooltip();
		$('.collapsible').collapsible();
		$('.slider').slider({
			full_width: true,
			height : 840,
			interval: 8000
		});
	});
</script>
<!--materialize CDN js-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>

</html>

templates/log_in.html
{% extends "index.html" %}
{% block content %}
<!--log in page is here you can navigate-->

	<div class="log_in container z-depth-3 hoverable flow-text input-field" >
		<div class="input-field">

		 <form class="site-form validate " method="POST" >
			{% csrf_token %}
			{{form.as_p}}

			{%if request.GET.next%}
			
			<input class="" type="hidden" name="next" value="{{request.GET.next}}">
			{%endif%}
			<input type="submit" class="btn waves-effect blue darken-2" value="Login" name="">

		 </form>
		</div>

	</div>




{% endblock content %}

templates/lost_found.html
{% extends "index.html" %}
{%load static%}

{% block content %}

{% for item in items_from_database %}
<div class="each_item container">

    <div class="row">
        <div class="col s4">
            <img class="responsive-img" src="{{item.image.url}}">
        </div>
        <div class="col s8">
            <h5>{{item.item_name}}</h5>
            <p><a href="#">{{item.snippet}}</a></p>
            <p><a href="#" style="color: grey;">{{item.date}}</a></p>
        </div>

    </div>

</div>
{%endfor%}

{% endblock content %}
<!--{% url 'items:details_of_items' slug_path=item_article.slug_path %}-->

templates/lost_found_items.html
<!--{% extends "index.html" %}-->
<!--{% block content %}-->


<!--<div class="item_detail container">-->
<!--    <h1><a href="">{{item.item_name}}</a></h1>-->
<!--    <img src="{{item.thumb.url}}">-->
<!--    <p><a href="#">{{item.item_description}}</a></p>-->
<!--    <p><a href="#">{{item.date}}</a></p>-->
<!--</div>-->



<!--{% endblock content %}-->

templates/sign_up.html
{% extends "index.html" %}
{% block content %}
<!--here is the page which you can navigate all sign up forms-->

	<div class="sign_up container z-depth-3 hoverable ">
		<form class="site-form input-field" method="POST" >
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" class="btn waves-effect waves-light blue darken-2" value="Sign up" name="">
		</form>
	</div>

{% endblock content %}